#pragma once


//From SFML

/* Printable keys */
#define HR_KEY_UNKNOWN             -1
#define HR_KEY_A                    0
#define HR_KEY_B                    1
#define HR_KEY_C                    2
#define HR_KEY_D                    3
#define HR_KEY_E                    4
#define HR_KEY_F                    5
#define HR_KEY_G                    6
#define HR_KEY_H                    7
#define HR_KEY_I                    8
#define HR_KEY_J                    9
#define HR_KEY_K                    10
#define HR_KEY_L                    11
#define HR_KEY_M                    12
#define HR_KEY_N                    13
#define HR_KEY_O                    14
#define HR_KEY_P                    15
#define HR_KEY_Q                    16
#define HR_KEY_R                    17
#define HR_KEY_S                    18
#define HR_KEY_T                    19
#define HR_KEY_U                    20
#define HR_KEY_V                    21
#define HR_KEY_W                    22
#define HR_KEY_X                    23
#define HR_KEY_Y                    24
#define HR_KEY_Z                    25
#define HR_KEY_NUM0                 26
#define HR_KEY_NUM1                 27
#define HR_KEY_NUM2                 28
#define HR_KEY_NUM3                 29
#define HR_KEY_NUM4                 30
#define HR_KEY_NUM5                 31
#define HR_KEY_NUM6                 32
#define HR_KEY_NUM7                 33
#define HR_KEY_NUM8                 34
#define HR_KEY_NUM9                 35
#define HR_KEY_ESCAPE               36
#define HR_KEY_LCONTROL             37
#define HR_KEY_LSHIFT               38
#define HR_KEY_LALT                 39
#define HR_KEY_LSYSTEM              40
#define HR_KEY_RCONTROL             41
#define HR_KEY_RSHIFT               42
#define HR_KEY_RALT                 43
#define HR_KEY_RSYSTEM              44
#define HR_KEY_MENU                 45
#define HR_KEY_LBRACKET             46
#define HR_KEY_RBRACKET             47
#define HR_KEY_SEMICOLON            48
#define HR_KEY_COMMA                49
#define HR_KEY_PERIOD               50
#define HR_KEY_QUOTE                51
#define HR_KEY_SLASH                52
#define HR_KEY_BACKSLASH            53
#define HR_KEY_TILDE                54
#define HR_KEY_EQUAL                55
#define HR_KEY_DASH                 56
#define HR_KEY_SPACE                57
#define HR_KEY_RETURN               58
#define HR_KEY_BACKSPACE            59
#define HR_KEY_TAB                  60
#define HR_KEY_PAGEUP               61
#define HR_KEY_PAGEDOWN             62
#define HR_KEY_END                  63
#define HR_KEY_HOME                 64
#define HR_KEY_INSERT               65
#define HR_KEY_DELETE               66
#define HR_KEY_ADD                  67
#define HR_KEY_SUBTRACT             68
#define HR_KEY_MULTIPLY             69
#define HR_KEY_DIVIDE               70
#define HR_KEY_LEFT                 71
#define HR_KEY_RIGHT                72
#define HR_KEY_UP                   73
#define HR_KEY_DOWN                 74
#define HR_KEY_NUMPAD0              75
#define HR_KEY_NUMPAD1              76
#define HR_KEY_NUMPAD2              77
#define HR_KEY_NUMPAD3              78
#define HR_KEY_NUMPAD4              79
#define HR_KEY_NUMPAD5              80
#define HR_KEY_NUMPAD6              81
#define HR_KEY_NUMPAD7              82
#define HR_KEY_NUMPAD8              83
#define HR_KEY_NUMPAD9              84
#define HR_KEY_F1                   85
#define HR_KEY_F2                   86
#define HR_KEY_F3                   87
#define HR_KEY_F4                   88
#define HR_KEY_F5                   89
#define HR_KEY_F6                   90
#define HR_KEY_F7                   91
#define HR_KEY_F8                   92
#define HR_KEY_F9                   93
#define HR_KEY_F10                  94
#define HR_KEY_F11                  95
#define HR_KEY_F12                  96
#define HR_KEY_F13                  97
#define HR_KEY_F14                  98
#define HR_KEY_F15                  99
#define HR_KEY_PAUSE                100
#define HR_KEY_KEYCOUNT             101